name: Build FRC Java with Gradle 2

on:
  - push

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        cd "RobotCode2020"
        .\gradlew.bat build
